config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    resources :articles
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord  
      belongs_to :user 
      validates :title, presence: true, length: { minimum: 6, maximum: 100 }
      validates :descripcion, presence: true, length: { minimum: 10, maximum: 300 }
end 

app/models/user.rb
class User < ApplicationRecord 
      before_save { self.email = email.downcase }
      has_many :articles 
      validates :username, presence: true,  
                                                uniqueness: {case_sensitive: false}, 
                                                length: {minimum: 3, maximum: 25}

      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

      validates :email, presence: true, 
                                                uniqueness: {case_sensitive: false}, 
                                                length: {maximum: 100},
                                                format: {with: VALID_EMAIL_REGEX}

      has_secure_password 

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

      helper_method :current_user, :logged_in?
      def current_user
            @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end 

      def logged_in?
            !!current_user
      end 

      def require_user 
            if !logged_in?
                  flash[:notice] = "Debes iniciar sesión!"
                  redirect_to login_path
            end 
      end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
      before_action :set_article, only: [:show, :edit, :update, :destroy]
      before_action :require_user, except: [:show, :index]
      before_action :require_same_user, only: [:edit, :update, :destroy]

      def show 
      end 

      def index
            @articles = Article.paginate(page: params[:page], per_page: 5)
      end 

      def new 
            @article = Article.new 
      end 

      def edit 
      end 

      def create 
            @article = Article.new(article_params) 
            @article.user = current_user 
            if @article.save 
                  flash[:notice] = "Articulo creado correctamente."
                  redirect_to article_path(@article)
            else 
                  render 'new'
            end  
      end 

      def update 
            if @article.update(article_params)
                  flash[:notice] = "Articulo actualizado correctamente."
                  redirect_to @article 
            else
                  render 'edit'
            end  
      end 

      def destroy 
            @article.destroy
            redirect_to articles_path 
      end 

      private 
      def set_article 
            @article = Article.find(params[:id])
      end 

      def article_params 
            params.require(:article).permit(:title, :descripcion)
      end 

      def require_same_user
            if current_user != @article.user
                  flash[:alert] = "Solo puedes editar o eliminar tus articulos"
                  redirect_to @article 
            end 
      end 

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
      def home 
            redirect_to articles_path if logged_in?
      end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
      def new 
      
      end 

      def create 
            user = User.find_by(email: params[:session][:email].downcase)
            if user && user.authenticate(params[:session][:password])
                  session[:user_id] = user.id 
                  flash[:notice] = "Inicio sesión con exito"
                  redirect_to user
            else 
                  flash.now[:alert] = "Algo salió mal :("
                  render 'new'
            end 
      end 

      def destroy
            session[:user_id] = nil 
            flash[:notice] = "Ah cerrado sesión"
            redirect_to root_path
      end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
      before_action :set_user, only: [:show, :edit, :update, :destroy]
      before_action :require_user, only: [:edit, :update]
      before_action :require_same_user, only: [:edit, :update]

      def show 
            @articles = @user.articles.paginate(page: params[:page], per_page: 5) 
      end 

      def index 
            @users = User.paginate(page: params[:page], per_page: 5)
      end 

      def new 
            @user = User.new
      end 

      def edit 
      end 

      def update 
          if @user.update(user_params)
            flash[:notice] = "Tu perfil ha sido actualizado"
            redirect_to @user
          else
            render 'edit'
          end 
      end 

      def create 
            @user = User.new(user_params)
            if @user.save 
                  session[:user_id] = @user.id
                  flash[:notice] = "Bienvenido a  Articulos, #{@user.username}"
                  redirect_to articles_path
            else
                  render 'new'
            end  
      end 

      def destroy 
            if @user.destroy 
                  flash[:alert] = "Se ha eliminado tu cuenta"
                  session[:user_id] = nil 
                  redirect_to root_path  
            else  
                  redirect_to articles_path
            end
      end 

      private 
      def user_params
            params.require(:user).permit(:username, :email, :password)
      end 

      def set_user
            @user = User.find(params[:id])
      end 

      def require_same_user
            if current_user != @user 
                  flash[:alert] = "Solo puedes editar tu perfil"
                  redirect_to @user 
            end 
      end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
      def gravatar_for(user, options = {size: 80})
            email_address = user.email.downcase
            hash = Digest::MD5.hexdigest(email_address)
            size = options[:size]
            gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
            image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
      end 

end

app/views/articles/_article.html.erb
<div class="container-fluid">
      <% @articles.each do |article| %>
            <div class="row justify-content-md-center">
                  <div class="col-8 mb-4">
                        <div class="card text-center shadow mb-5 bg-white rounded"">
                              <div class="card-header font-italic">
                                    <% if article.user %>
                                          de <%= link_to article.user.username, user_path(article.user) %>
                                    <% end %>
                              </div>
                                    <div class="card-body">
                                          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-info" %></h5>
                                          <p class="card-text"><%= truncate(article.descripcion, length: 100) %></p>
                                          <%= link_to 'Ver', article_path(article.id), class: "btn btn-outline-success"%>
                                          <% if logged_in? %>
                                                <%= link_to 'Editar', edit_article_path(article.id), class: "btn btn-outline-primary"%>
                                                <%= link_to 'Eliminar', article_path(article.id), method: :delete, data: {confirm: "¿Estás seguro?"}, class: "btn btn-outline-danger"%>
                                          <% end %>
                                    </div>
                              <div class="card-footer text-muted">
                                    <small>Creado: <%= time_ago_in_words(article.created_at) %>,
                                                      Editado: <%= time_ago_in_words(article.updated_at) %>
                                    </small>
                              </div>
                        </div>
                  </div>
            </div>
      <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
      <div class="row justify-content-center">
            <div class="col-10">
            <%= render 'shared/errors', obj: @article %>
                  <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>
                        <div class="form-group row text-white">
                              <%= f.label :title, class: "col-2 col-form-label" %>
                              <div class="col-10">
                                    <%= f.text_field :title, class: "form-control" %>
                              </div> 
                        </div>

                        <div class="form-group row text-white">
                              <%= f.label :descripcion, class: "col-2 col-form-label" %>
                              <div class="col-10">
                                    <%= f.text_area :descripcion, rows: 10, class: "form-control" %>
                              </div>
                        </div>   

                        <div class="form-group row justify-content-center">
                              <%= f.submit(@article.new_record? ? "Crear Articulo" : "Actualizar Articulo", class: "btn btn-outline-light btn-lg") %>
                        </div>
                  <% end %>
            </div>
      </div>
      <div class="text-center font-weight-bold mb-5">
            <%= link_to '[ Regresar a los articulos ]', articles_path, class: "text-dark"%>
      </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center my-3">Editar articulo</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center my-3">Lista de articulos</h1>
<div class="flickr_pagination my-2">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination my-2">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center my-3">Crear un articulo</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center my-3"><%= @article.title%></h1>

<div class="container-fluid">
            <div class="row justify-content-md-center">
                  <div class="col-8 mb-4">
                        <div class="card text-center shadow mb-5 bg-white rounded"">
                              <div class="card-header font-italic">
                              de <%= @article.user.username if @article.user %> 
                              <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                              </div>
                                    <div class="card-body">
                                          <div class="card-text text-left"><%= simple_format(@article.descripcion) %></div>
                                          <% if logged_in? %>
                                                <%= link_to 'Editar', edit_article_path(@article), class: "btn btn-outline-primary"%>
                                                <%= link_to 'Eliminar', article_path(@article), method: :delete, data: {confirm: "¿Estás seguro?"}, class: "btn btn-outline-danger"%>
                                          <% end %>
                                    </div>
                              <div class="card-footer text-muted">
                                    <small>Creado: <%= time_ago_in_words(@article.created_at) %>,
                                                      Editado: <%= time_ago_in_words(@article.updated_at) %>
                                    </small>
                              </div>
                        </div>
                              <div class="text-center font-weight-bold mb-5">
                        <%= link_to '[ Regresar a los articulos ]', articles_path, class: "text-dark"%>
                        </div>
                  </div>
            </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
      <div class="container text-center">
        <small>Copyright &copy; <%= link_to "LeninJo", "https://google.com", class: "text-white"%></small>
      </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container-flui">
    <% flash.each do |name, msg| %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= msg %>   
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
      </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Blog's Articulos", root_path, class: "navbar-brand font-weight-bold text-uppercase"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link text-white"%>
        </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articulos
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Ver articulos", articles_path, class: "dropdown-item"%>
              <% if logged_in? %>
                <%= link_to "Crear articulo", new_article_path, class: "dropdown-item"%>
              <% end %>
            </div>
          </li>
        </ul>
      <div>
        <ul class="navbar-nav mr-auto">
          <% if logged_in?%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Perfil", user_path(current_user), class: "dropdown-item"%>
                <div class="dropdown-divider"></div>
                <%= link_to "Cerrar sesión", logout_path, method: :delete, class: "dropdown-item"%>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Iniciar sesión", login_path, class: "nav-link mx-1 btn btn-info btn-sm text-white"%>
            </li>
            <li class="nav-item">
              <%= link_to "Registrarme", signup_path, class: "nav-link mx-1 btn btn-success btn-sm text-white"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articulos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid py-3">
      <div class="jumbotron jumbotron">
            <div class="container text-white text-center">
                  <h1 class="display-4">CRUD - Articulos</h1>
                  <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
                  <hr class="my-4">
                  <%= link_to "Registrarme", signup_path, class: "btn btn-success btn-lg"%>
            </div>
      </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <h5 class="alert-heading">Algunos errores impiden que <%= obj.class.name.downcase %> se guarde</h5>
            <ul>
                  <% obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                  <% end %>
            </ul>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
            </button>
      </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
      <div class="row justify-content-center">
            <div class="col-6">
            <%= render 'shared/errors', obj: @user %>
                  <%= form_with(model: @user, class: "shadow p-4 mb-3 bg-dark rounded", local: true) do |f| %>
                        <div class="form-group row text-white">
                              <%= f.label :username, class: "col-2 col-form-label" %>
                              <div class="col-10">
                                    <%= f.text_field :username, class: "form-control", placeholder: "Nombre de usuario" %>
                              </div>
                        </div>
                        <br>
                        <div class="form-group row text-white">
                              <%= f.label :email, class: "col-2 col-form-label" %>
                              <div class="col-10">
                                    <%= f.email_field :email, class: "form-control", placeholder: "Email"%>
                              </div>
                        </div>   
                        <br>
                        <div class="form-group row text-white mb-4">
                              <%= f.label :password, class: "col-2 col-form-label" %>
                              <div class="col-10">
                                    <%= f.password_field :password, class: "form-control", placeholder: "Contraseña"%>
                              </div>
                        </div>   

                        <div class="form-group row justify-content-center">
                              <%= f.submit(@user.new_record? ? "Registrarme" : "Actualizar", class: "btn btn-outline-light btn-lg") %>
                        </div>
                  <% end %>
            </div>
      </div>
      <div class="text-center font-weight-bold my-5">
            <%= link_to '[ Regresar a los articulos ]', articles_path, class: "text-dark"%>
      </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center my-3">Editar mi perfil</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center my-3">Usuarios de Articulos</h1>
<div class="flickr_pagination my-2">
    <%= will_paginate @users, :container => false %>
</div>
<div class="container-fluid">
      <% @users.each do |user| %>
            <div class="row justify-content-md-center">
                  <div class="col-8 mb-4">
                        <div class="card text-center shadow mb-5 bg-white rounded"">
                              <div class="card-header font-italic">
                              <%= link_to user.username, user %>
                              </div>
                                    <div class="card-body">
                                          <h5 class="card-title">
                                                <%= link_to gravatar_for(user, size: 150), user %>
                                          </h5>
                                          <p class="card-text"><%= pluralize(user.articles.count, "articulos") %></p>
                                          <%= link_to 'Ver perfil', user, class: "btn btn-outline-success"%>
                                          <% if logged_in? %>
                                                <%= link_to 'Editar perfil', edit_user_path(user), class: "btn btn-outline-primary" %>
                                          <% end %>
                                    </div>
                              <div class="card-footer text-muted">
                                    <small>Unido: <%= time_ago_in_words(user.created_at) %>
                                    </small>
                              </div>
                        </div>
                  </div>
            </div>
      <% end %>
</div>
<div class="flickr_pagination my-2">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center my-3">Registrarme</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center my-3"><strong><%= @user.username %></strong></h1>
<h5 class="text-center my-3"><%= @user.email %></h5>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to  "Editar perfil", edit_user_path(@user), class: "btn btn-outline-dark" %>
        <br>
        <br>
        <%= link_to '[ Eliminar cuenta ]', user_path(@user), method: :delete, data: {confirm: "¿Estás seguro?"}, class: "text-danger" %>
    </div>
<% end %>
<hr>
<h4 class="text-center my-3">Articulos creados</h4>
<div class="flickr_pagination my-2">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/article' %>
<div class="flickr_pagination my-2">
    <%= will_paginate @articles, :container => false %>
</div>